### ISSUE TITLE
add CI jobs to generate yaml files to install with kubectl

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/kubernetes-csi-addons#107]
This should probably become an artifact when we do a release. Creating a tag in git can then generate the yaml, and post it as part of the release (somehow). It requires adding one or more jobs to the `build-push` workflow we already have.

_Originally posted by @nixpanic in https://github.com/csi-addons/kubernetes-csi-addons/pull/106#discussion_r794500631_

**Comment by nixpanic** [comment]
[release-action](https://github.com/ncipollo/release-action) is one tool that could assist with this
