### ISSUE TITLE
Add github actions for static tools

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/kubernetes-csi-addons#12]
Add GitHub actions for static tools.

- [x] golint
- [ ] shellscripts
- [x] yaml files
- [x] .md files

etc.

**Comment by nixpanic** [comment]
golangci-lint was added with #365

**Comment by Madhu-1** [comment]
> don't have any shell scripts currently, so do we still want to have the github action for shellscripts?

IF we don't have it we can skip it. Thank you @riya-singhal31 , closing this as completed
