### ISSUE TITLE
Add deployment guide

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/kubernetes-csi-addons#14]
Add deployment guide which helps admins/users to deploy the csi-addons with different CSI drivers in standalone kubernetes/OCP clusters.

**Comment by nixpanic** [comment]
https://github.com/csi-addons/kubernetes-csi-addons#controller includes two options for deploying too.

[v0.3.0](https://github.com/csi-addons/kubernetes-csi-addons/releases/tag/v0.3.0) contains a `setup-controller.yaml` which ideally gets used for versioned (production) deployments. This is something that still should get added to the docs. @yati1998, do you want to do that?

**Comment by yati1998** [comment]
Yeah sure

**Comment by Madhu-1** [comment]
@yati1998 this is already done right?

**Comment by yati1998** [comment]
yes, we have docs/deploy-controller.md .
