### ISSUE TITLE
"error": "node Client not found"

### ISSUE THREAD

**Issue by liwh1111** [csi-addons/kubernetes-csi-addons#166]
Hello, I install the "kubernetes - csi - addons - 0.4.0", execute ReclaimSpaceJob error, is that where there is the problem

kubernetes version: 1.22
rook: 1.9.0

![image](https://user-images.githubusercontent.com/63097736/174556324-330f59e8-2f94-41bc-9fd9-e5ba76bacd9e.png)

**Comment by Rakshith-R** [comment]
@liwh1111 
Can you try with the latest version `quay.io/csiaddons/k8s-sidecar:v0.4.0`

and latest controller version too `quay.io/csiaddons/k8s-controller:v0.4.0` ?

**Comment by liwh1111** [comment]
Ok, I'll try
