### ISSUE TITLE
Csi-addons-controller-manager error after reclaimSpaceJob

### ISSUE THREAD

**Issue by liwh1111** [csi-addons/kubernetes-csi-addons#170]
kubernetes version: 1.20.14 (Does Kubernetes-CSI-Addons support Kubernetes version 1.20.14?)
rook version: 1.9.0

"csi-addons-controller-manager" error, What's wrong with this?
![image](https://user-images.githubusercontent.com/63097736/175451462-a0150038-038d-4e0c-a353-3b68bc50f1b1.png)

**Comment by Rakshith-R** [comment]
@liwh1111 can you check logs of pod csi-rbdplugin-45wp7 container csi-rbdplugin and csi-addons  ?

Does running reclaimspace job again on the same pvc fails again with same error ?

You can check output of -o yaml of the reclaimspace job.

**Comment by liwh1111** [comment]
![image](https://user-images.githubusercontent.com/63097736/175461093-a92c9130-2a93-4a91-b3f2-9c89f9117a65.png)

![image](https://user-images.githubusercontent.com/63097736/175461111-8906da27-4e13-4905-b3fa-bac1ea739a98.png)

![image](https://user-images.githubusercontent.com/63097736/175461142-fbec9d65-2f92-4413-b05a-c29b97da4650.png)

**Comment by Rakshith-R** [comment]
@liwh1111 can you check logs of pod csi-rbdplugin-provisioner-6ddf94f9c0... container csi-rbdplugin and csi-addons ?

Boosting log verbosity by setting `CSI_LOG_LEVEL: "5"` will help.
https://github.com/rook/rook/blob/c8658331df09cbef3b07b1ac3f60b28267ce1635/deploy/examples/operator.yaml#L47

**Comment by liwh1111** [comment]
log CSI_LOG_LEVEL: "5"

kubectl -n rook-ceph logs -f csi-rbdplugin-56twj csi-rbdplugin
![image](https://user-images.githubusercontent.com/63097736/175479721-01f29401-fa90-4416-b59c-4291ed40d38a.png)

kubectl -n rook-ceph logs -f csi-rbdplugin-56twj csi-addons
![image](https://user-images.githubusercontent.com/63097736/175480032-77990d3e-867a-4597-b86e-f6b737c09f75.png)

kubectl -n rook-ceph logs -f csi-rbdplugin-provisioner-f4d4dcd95-kpvtz csi-rbdplugin
![image](https://user-images.githubusercontent.com/63097736/175480141-5898f9d7-215d-4d4a-b882-5cf9b8608a68.png)

kubectl -n rook-ceph logs -f csi-rbdplugin-provisioner-f4d4dcd95-kpvtz csi-addons
![image](https://user-images.githubusercontent.com/63097736/175480266-01c48f6c-e363-4848-a784-de54943afecf.png)

Is there anything wrong with it?

**Comment by Rakshith-R** [comment]
@liwh1111 
the rbd sparsify command seems to be taking a long time to return 
Whats the size of the PVC and how much data is stored in it ? 
(maybe run `rbd du` ) ?
can you try running this command from toolbox ?
```
rbd sparsify <pool-name>/<image-name>
```
you can get pool name and image name from PV spec

**Comment by liwh1111** [comment]
![image](https://user-images.githubusercontent.com/63097736/175483715-90c44991-607e-46ff-a69e-ddb65b53ed59.png)
![image](https://user-images.githubusercontent.com/63097736/175486378-c9c8e029-0404-4ff8-aac0-a322e9cf9e9e.png)

Kafka-data is stored in this PVC,

rbd sparsify replicapool/csi-vol-69fcfc1c-f295-11ec-ad87-7a42f62343b1,   It took about seven minutes

**Comment by Rakshith-R** [comment]
> Kafka-data is stored in this PVC,
> 
> rbd sparsify replicapool/csi-vol-69fcfc1c-f295-11ec-ad87-7a42f62343b1, It took about seven minutes

That explains the timeout, 
the command will be executed on the ceph cluster but is not returning before context deadline is reached because the size is so large.
you can ignore this error. 
I do see the nodereclaim `fstrim` is successful.

Maybe setup a cronjob with suitable interval.

**Comment by liwh1111** [comment]
Thank you very much. Can I increase the "context deadline" to solve this problem? Do you know where to set it?

**Comment by Rakshith-R** [comment]
> Thank you very much. Can I increase the "context deadline" to solve this problem? Do you know where to set it?

https://github.com/csi-addons/kubernetes-csi-addons/blob/267719c6c579ab4ac5c8e342df6e15fc0bd0567e/cmd/manager/main.go#L67
https://github.com/csi-addons/kubernetes-csi-addons/blob/main/sidecar/main.go

@liwh1111 
Yes, can you try setting these timeouts for sidecar and controller  from the cmdline args.

**Comment by liwh1111** [comment]
I don't know go language, could you please tell me how to operate it

**Comment by liwh1111** [comment]
Ok, thank you

**Comment by Rakshith-R** [comment]
The newly added configmap option should be able to help in this.
Please upgrade to the latest csi addosn v0.7.0 version and try it out.

https://github.com/csi-addons/kubernetes-csi-addons/blob/main/docs/csi-addons-config.md

Closing this issue.

**Comment by Rakshith-R** [comment]
@liwh1111 ^
