### ISSUE TITLE
Add Replication capability to csi-addons admin/test tool

### ISSUE THREAD

**Issue by Rakshith-R** [csi-addons/kubernetes-csi-addons#207]
Add Replication capability to csi-addons admin/test tool along with currently supported reclaimspace and identity capability.

https://github.com/csi-addons/kubernetes-csi-addons/tree/main/cmd/csi-addons

**Comment by riya-singhal31** [comment]
Closes with: https://github.com/csi-addons/kubernetes-csi-addons/pull/419
