### ISSUE TITLE
Handle non implemented error for getVolumeReplicationInfo RPC

### ISSUE THREAD

**Issue by yati1998** [csi-addons/kubernetes-csi-addons#236]
We need to handle the nonimplemented error for RPC getVolumeReplication call.
For more details please check this:
https://github.com/csi-addons/kubernetes-csi-addons/pull/232#pullrequestreview-1105486946

**Comment by Madhu-1** [comment]
@yati1998 you are planning to fix this one soon?

**Comment by yati1998** [comment]
> @yati1998 you are planning to fix this one soon?

yes.
