### ISSUE TITLE
Add version flag for csi-addons-sidecar

### ISSUE THREAD

**Issue by saranyareddy24** [csi-addons/kubernetes-csi-addons#377]
Other than currents flags in /usr/bin/csi-addons-sidecar, need a new flag which displays version `-version`.

It will be helpful in our case, where we are building pipelines for image creation of csi-addons components, once the image is built, if we have the version displayed, it will be easy to add that as a verification step in pipeline.

**Comment by Madhu-1** [comment]
Looks like a good suggestion. added `good-first-issue`

**Comment by saranyareddy24** [comment]
I am working on it.
