### ISSUE TITLE
Add version flag for volume replication operator

### ISSUE THREAD

**Issue by saranyareddy24** [csi-addons/kubernetes-csi-addons#378]
Other than currents flags in `/manager`, need a new flag which displays version `-version`.

It will be helpful in our case, where we are building pipelines for image creation of csi-addons components, once the image is built, if we have the version displayed, it will be easy to add that as a verification step in pipeline.

**Comment by Madhu-1** [comment]
Looks like a good suggestion. added `good-first-issue`

**Comment by Madhu-1** [comment]
As add more details like below

Git commit, Go build,platform details
