### ISSUE TITLE
update Makefile to generate golang libs for interal protos

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/kubernetes-csi-addons#38]
currently, this is done manually whoever is pushing the PR. this should be added to makefile not everyone is aware of how to generate proto or what version to use

**Comment by Rakshith-R** [comment]
@Madhu-1 with the addition of https://github.com/csi-addons/kubernetes-csi-addons/pull/372 
it's gotten way easier to generate internal protos and I think that is sufficient.

Can we close this issue ?
