### ISSUE TITLE
All the Controller Operations should reach the one Controller (active) not multiple Controllers

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/kubernetes-csi-addons#422]
As of today, the kubernetes csi addons try to connect to the random controller that are registered and try to make the RPC calls to the random controller. This can create a problem if the csi driver has implemented some internal locking mechanism or has some local cache for the lifetime of that instance.

Example as below:-

CephCSI runs deployments for Replication/Reclaimspace etc and we will have two instances running. CephCSI Internally takes a lock and processes a request one at a time based on its internal logic. With the current kubernetes sidecar, it's not a problem because the sidecar runs with a leader election and only one can process a request but with kubernetes-csiaddons it becomes a problem as we don't have any such mechanism to reach the same controller/deployment which is processing the requests.

The request is to provide this kind of functionality so that it will be helpful for the CSI driver who is having this kind of requirement and moreover not to run active/active models as it can lead to many different models.

**Comment by nixpanic** [comment]
The csi-addons side-car should probably use a similar mechanism as the csi-provisioner and others. When the csi-addons sidecar detects that the csi-driver provides the `CONTROLLER_SERVICE` capability, it should try to obtain a [lease](https://kubernetes.io/docs/concepts/architecture/leases/#custom-workload) for the driver.

The kubernetest-csi-addons Operator should only send controller operations to the csi-driver pod that holds the lease for that particular driver.

**Comment by Rakshith-R** [comment]
- Add another field `ConnectedAt` in Connection struct 
https://github.com/csi-addons/kubernetes-csi-addons/blob/0fe08b80cc8f98b70050b8ec128a2949b95f7d98/internal/connection/connection.go#L30-L36

- Fill it while adding connection to pool
https://github.com/csi-addons/kubernetes-csi-addons/blob/0fe08b80cc8f98b70050b8ec128a2949b95f7d98/internal/connection/connection_pool.go#L40

- Sort based on ConnectedAt timestamp and use the oldest client

**Comment by nixpanic** [comment]
A `ConnectedAt` timestamp may not be stable enough. I guess it is possible that the Kubernetes API is not working correctly anymore (some partial network issue?), but the operator and side-car are still connected. This would cause any operation on the side-car to fail when the Kubernetes API is used (almost all operations need to fetch secrets).

Using the Leases API will make sure the Kubernetes API is functioning the way it should. If it does not, the side-car can not extend the lease and it will expire, allowing an other side-car to become the acting controller service.

**Comment by Madhu-1** [comment]
Having a lease is more kubernetes way instead of hacking with the timestamp 👍🏻 we can introduce a flag in sidecar to run with leader election and we can use csi driver name+some const value to take the lease (just a thought).  we don't need to introduce extra logic in the controller and we can make use of the same model like kubernetes csi sidecars as well.

**Comment by nixpanic** [comment]
Ideally no flag is needed, and the side-car decides if a lease is needed (`CONTROLLER_SERVICE` is a capability returned by the csi-driver). The name of the lease can be based on the name of the csi-driver and adding `csi-addons` somewhere.

The operator would inspect the lease, and see which Pod holds it, before sending the operation to the controller.

**Comment by nixpanic** [comment]
Seamless upgrading would be great to have. It should be allowed to have a mix of versions installed, as the Operator deployment does not influence the side-car version that is deployed with CSI-drivers.

In order to make this work, the side-car should announce a capability that indicates it supports leader-election. The Operator can then decide to send the procedure only to the leading side-car. For drivers (with old side-car) that do not announce the capability, the Operator can randomly pick a side-car.

If the side-car announces the capability, but the Operator does not support it (old Operator version), it should be ignored and the current behavior should be unaltered. This means that the side-car should not check if it is the leader before executing the procedure, even if the side-car supports leader election, it should accept and execute procedures.
