### ISSUE TITLE
In case the CSIAddonsNode CRD is not available, the sidcar should not abort but retry

### ISSUE THREAD

**Issue by nixpanic** [csi-addons/kubernetes-csi-addons#48]
When the sidecar fails to create the CSIAddonsNode, it fails, and causes a deployment/deamonset of the CSI-driver to fail.

It is better to report the error of the missing CRD and the failure, and backoff-retry until the CRD becomes available (might be never). This will allow deploying the sidecar by default, even when users do not deploy the controller and the CRDs.

**Comment by Madhu-1** [comment]
This is applicable to the controllers also. if any of the CRD is missing the operator should not crash instead of that the operator should be try with back-off

**Comment by Rakshith-R** [comment]
> When the sidecar fails to create the CSIAddonsNode, it fails, and causes a deployment/deamonset of the CSI-driver to fail.


This was partially intentional, since the user may not notice missing CRDs until they look inside sidecar logs but sidecar being crashloop backoff would make a bit more prominent. Note: only sidecar will be crashloopbackoff.

> It is better to report the error of the missing CRD and the failure, and backoff-retry until the CRD becomes available (might be never). This will allow deploying the sidecar by default, even when users do not deploy the controller and the CRDs.
 
 I am okay with backoff-retry method too. 
 
 
---
> This is applicable to the controllers also.

I have not seen any of the controllers wait explicitly for core CRDs which it is supposed to be watching with backoff-retry.
(volrep being exception, I inferred so since it is part of cephcsi deployment and unique)

>if any of the CRD is missing the operator should not crash instead of that the operator should be try with back-off

controller will not crash but will internally retry 
example  with only reclaimspacejob CRD missing
```
W0107 05:20:10.003375       1 reflector.go:324] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: failed to list *v1alpha1.ReclaimSpaceJob: the server could not find the requested resource (get reclaimspacejobs.csiaddons.openshift.io)
E0107 05:20:10.003409       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: Failed to watch *v1alpha1.ReclaimSpaceJob: failed to list *v1alpha1.ReclaimSpaceJob: the server could not find the requested resource (get reclaimspacejobs.csiaddons.openshift.io)
W0107 05:21:00.856224       1 reflector.go:324] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: failed to list *v1alpha1.ReclaimSpaceJob: the server could not find the requested resource (get reclaimspacejobs.csiaddons.openshift.io)
E0107 05:21:00.856300       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: Failed to watch *v1alpha1.ReclaimSpaceJob: failed to list *v1alpha1.ReclaimSpaceJob: the server could not find the requested resource (get reclaimspacejobs.csiaddons.openshift.io)
```

example with csiaddonsnode CRd missing too:
```
W0107 05:22:30.711839       1 reflector.go:324] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: failed to list *v1alpha1.CSIAddonsNode: the server could not find the requested resource (get csiaddonsnodes.csiaddons.openshift.io)
E0107 05:22:30.712171       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: Failed to watch *v1alpha1.CSIAddonsNode: failed to list *v1alpha1.CSIAddonsNode: the server could not find the requested resource (get csiaddonsnodes.csiaddons.openshift.io)

W0107 05:22:40.113255       1 reflector.go:324] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: failed to list *v1alpha1.ReclaimSpaceJob: the server could not find the requested resource (get reclaimspacejobs.csiaddons.openshift.io)
E0107 05:22:40.113290       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: Failed to watch *v1alpha1.ReclaimSpaceJob: failed to list *v1alpha1.ReclaimSpaceJob: the server could not find the requested resource (get reclaimspacejobs.csiaddons.openshift.io)
```

They do not crash, so I guess we can let the controller runtime take care of retries. 

Adding explicit retry will block starting multiple controller since they are started sequential.

**Comment by Madhu-1** [comment]
> > When the sidecar fails to create the CSIAddonsNode, it fails, and causes a deployment/deamonset of the CSI-driver to fail.
> 
> This was partially intentional, since the user may not notice missing CRDs until they look inside sidecar logs but sidecar being crashloop backoff would make a bit more prominent. Note: only sidecar will be crashloopbackoff.
> 
> > It is better to report the error of the missing CRD and the failure, and backoff-retry until the CRD becomes available (might be never). This will allow deploying the sidecar by default, even when users do not deploy the controller and the CRDs.
> 
> I am okay with backoff-retry method too.
> 
> > This is applicable to the controllers also.
> 
> I have not seen any of the controllers wait explicitly for core CRDs which it is supposed to be watching with backoff-retry. (volrep being exception, I inferred so since it is part of cephcsi deployment and unique)
>

Please note this is a generic operator, not everyone will make use of all the CRD's or install on the CRD to make the controller work.

> > if any of the CRD is missing the operator should not crash instead of that the operator should be try with back-off
> 
> controller will not crash but will internally retry example with only reclaimspacejob CRD missing
> 

If the controller is not crashing then we are good.

**Comment by nixpanic** [comment]
@Rakshith-R not sure if there is anything to do for the controller? #51 addresses the crashing of the sidecar.

**Comment by Rakshith-R** [comment]
> @Rakshith-R not sure if there is anything to do for the controller? #51 addresses the crashing of the sidecar.

Controller runtime will error out and take care of retrying when CRD is not found.
So #51 should be sufficient to close this issue.
