### ISSUE TITLE
Consider using NetworkPolicies to allow/deny access to the CSI-driver sidecar

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/kubernetes-csi-addons#643]
the kube-proxy container has a warning for insecure access https://github.com/kubernetes-sigs/kubebuilder/pull/3899, we need to adopt as per https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/discontinue_usage_of_kube_rbac_proxy.md

**Comment by nixpanic** [comment]
Fome rge [summary](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/discontinue_usage_of_kube_rbac_proxy.md#summary):

> Existing users are encouraged to switch to images hosted by the project on [quay.io](https://quay.io/repository/brancz/kube-rbac-proxy?tab=tags&tag=latest) OR to adapt their projects to utilize [Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/), following the updated scaffold guidelines.

NetworkPolicies would require additional configuration on the deployment by users. They need to open-up the port of the CSI-Addons sidecar that is running as part of their CSI-driver. This requires a bit more consideration than replacing the container-image repository.
