### ISSUE TITLE
Provide an email address to get in contact with maintainers and contributors

### ISSUE THREAD

**Issue by nixpanic** [csi-addons/kubernetes-csi-addons#67]
While working on #66, it became obvious that there is a need for an email address that can be used for contacting maintainers of the project. I'd like to know 

a. Google group (like [CSI](https://groups.google.com/forum/#!forum/container-storage-interface-community))
b. an email list [maintained by Red Hat IT](https://listman.redhat.com/) (will have `@redhat.com` as domain)
c. email gateway to create an issue (like [Fire](https://fire.fundersclub.com/))
d. .... something else?

My preference would be either **b** or **c**.

**Comment by Madhu-1** [comment]
@nixpanic can you help me with option b? i will talk to you offline for this one

**Comment by humblec** [comment]
@nixpanic the concern with option b is, this becomes a company tied project, isnt it ? I would suggest an open forum or channel for this repo than Red Hat one. In that sense option A looks better to me

**Comment by nixpanic** [comment]
> 

It is not exclusive to Red Hat only projects, there are mailinglists hosted for several community projects there too.

**Comment by nixpanic** [comment]
csi-addons@redhat.com has been created, there are several ways to subscribe to the list:

- send an email to [csi-addons-request@redhat.com](mailto:csi-addons-request@redhat.com?subject=subscribe) with subject `subscribe`
- through the [mailman web interface](https://listman.redhat.com/mailman/listinfo/csi-addons)

If there are any difficulties, reach out to the [mailinglist managers](csi-addons-owner@redhat.com).
