### ISSUE TITLE
use docker cache to build images

### ISSUE THREAD

**Issue by Madhu-1** [csi-addons/kubernetes-csi-addons#719]
Currently it takes around 2 hours to build the sidecar and the controller images, it would be good to see if we can use docker cache to fasten the build process.

**Comment by nixpanic** [comment]
The thing that makes it slow is building for arm/v7. We do not really need that architecture IMHO. All reasonable ARM systems are now arm64/aarch64.

**Comment by Madhu-1** [comment]
Sounds good 👍🏻

**Comment by nixpanic** [comment]
With the proposed change to build without linux/arm/v7, building the container-images takes less than 5 minutes (was almost 2 hours).
