### ISSUE TITLE
CSV version should match with the tag of the bundle image

### ISSUE THREAD

**Issue by iamniting** [csi-addons/kubernetes-csi-addons#82]
Image: `quay.io/csiaddons/k8s-bundle:v0.1.1`
CSV name: `csi-addons.v0.0.1`

We have multiple bundles in the odf-operator and all of them use the tag same as a CSV version. We would like CSI addons to do the same. Either we should change the CSV version or tag of the image to match both.

**Comment by nixpanic** [comment]
That can be done. The CSV/bundle version does usually not need that many version changes, but I guess it does not hurt either.
