### ISSUE TITLE
Add github actions ci to test builds and push images

### ISSUE THREAD

**Issue by Rakshith-R** [csi-addons/kubernetes-csi-addons#9]
This issue is to track following items: 

- [x] Decide name for controller and sidecar images (Please comment down suggestions)
- [x] Add build scripts for controller and sidecar images
- [x] Add ci to run go test and build
- [x] Add multi architechure build test
- [x] Add github action to push images to registry.

Please add any missing item from the list in the comments below.

**Comment by nixpanic** [comment]
workflows for most of the topics already exist under `.github/workflows`.

#33 adds initial Golang (`vendor/` verification) and can be extended to run `go test`.

**Comment by nixpanic** [comment]
* #42 add `go test` and related checks
* `.github/workflows/test-build.yaml` takes care of building images for testing
* `.github/workflows/build-push.yaml` pushes the images to Quay.
